version: "2.4"
services:
  db:
    image: postgres:latest
    container_name: postgres_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pagila
    volumes:
      - ./pagila:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    mem_limit: "512m"
    cpus: 1.0

  backend:
    build: ./backend
    container_name: web_server
    ports:
      - 8000:8000
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: pagila
    depends_on:
      - db
    mem_limit: "256m"
    cpus: 0.5
